title: Quadruped Blog - Inverse Kinematics implemented on 3DOF quadruped
description: Quadruped Blog - Inverse Kinematics implemented on 3DOF quadruped
author: Wojciech Rutkowski
logo: /quadruped/static/img/quadruped.png
github: https://github.com/wrutkowski
about: Robot enthusiast

baseurl: "/quadruped"
url: "https://wrutkowski.github.io/quadruped"

share:
  twitter_username: WojRutkowski

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
